name: self

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, Linux, X64, amd64-main]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: make
        run: make

