name: self

on:
  workflow_dispatch:

jobs:

  check:
    runs-on: [self-hosted, Linux, X64, amd64-main]
    timeout-minutes: 7200
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check keygen
        run: jasminc ml_dsa_65/ref/ml_dsa.jazz -checksafety -slice ml_dsa_65_keygen

